name: develop

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
  MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}

permissions: {}

jobs:
  devCheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install pnpm
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6
        with:
          version: 10

      - name: Install mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
        with:
          experimental: true
          install: false

      - name: Setup Node.js version from mise
        run: |
          NODE_VERSION=$(mise list node --json | jq -r '.[0].version')
          echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm check

      - name: type-check
        run: pnpm type-check

      - name: Test
        run: pnpm test:run
