name: develop

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
  MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: install node_modules
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: npm run test

      - name: build
        env:
          APP_ENV: "development"
        run: npm run build --if-present
